on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BDUSS: 'BDUSS'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: npm install, build, and test
      run: |
        npm run test


