name: Node.js CI

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  BDUSS: ${{ secrets.BDUSS }}
  proxy: ${{ secrets.proxy }}
  corpId: ${{ secrets.corpId }}
  corpSecret: ${{ secrets.corpSecret }}
  agentId: ${{ secrets.corpSecret }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/main@7d725b21b0a0b886e7ec7a785684a3f504a8bee1
    - run: npm i
    - run: npm test
